#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;

const string YES = "Yes";
const string NO = "No";

void solveCase(ll N, const vector<vector<ll>> &C)
{
    // TODO: edit here
    int idx = 0;
    for (size_t i = 0; i < N; i++)
        if (C[i][0] < C[idx][0])
            idx = i;
    vector<ll> a(N, -1), b(N, -1);
    a[idx] = 0;
    b = C[idx];
    db(idx, b);
    for (size_t i = 0; i < N; i++)
    {
        if (i == idx)
            continue;
        a[i] = C[i][0] - b[0];
        if (a[i] < 0)
        {
            cout << "No\n";
            return;
        }
        for (size_t j = 1; j < N; j++)
        {
            ll b_j = C[i][j] - a[i];
            if (b_j != b[j])
            {
                cout << "No\n";
                return;
            }
        }
    }
    cout << "Yes\n";
    for (auto &x : a)
        cout << x << ' ';
    cout << '\n';
    for (auto &x : b)
        cout << x << ' ';
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main()
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    ll N;
    cin >> N;
    vector<vector<ll>> C(N, vector<ll>((N)));
    for (int i = 0; i < N; ++i)
        for (int j = 0; j < N; ++j)
        {
            {
                cin >> C[i][j];
            }
        }
    solveCase(N, C);
    // cout << No << endl;
    return 0;
}