#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;

const string YES = "Yes";
const string NO = "No";
bool solveCase(int64_t A, int64_t B, int64_t C, int64_t D)
{
    // TODO: edit here
    vector<int64_t> arr;
    arr.pb(A);
    arr.pb(B);
    arr.pb(C);
    arr.pb(D);
    for (size_t i = 1; i < (1 << 4); i++)
    {
        int64_t suma = 0, sumb = 0;
        for (size_t j = 0; j < 4; j++)
        {
            if ((i >> j) & 1)
                suma += arr[j];
            else
                sumb += arr[j];
        }
        if (suma == sumb)
            return 1;
    }
    return 0;
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main()
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    int64_t A, B, C, D;
    cin >> A >> B >> C >> D;
    auto ans = solveCase(A, B, C, D);
    cout << (ans ? YES : NO) << endl;
    return 0;
}