#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;

int64_t solveCase(int64_t not_fat, int64_t fat)
{
    // TODO: edit here
    ll solid = fat + not_fat;
    if (solid >= 15 && fat >= 8)
        cout << "1\n";
    else if (solid >= 10 && fat >= 3)
        cout << "2\n";
    else if (solid >= 3)
        cout << "3\n";
    else
        cout << "4\n";
    return 0;
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main()
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    int64_t A, B;
    cin >> A >> B;
    auto ans = solveCase(A, B);
    // cout << ans << endl;
    return 0;
}