#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;


int64_t solveCase(int N, int K, const vector<int64_t> & a, const vector<int64_t> & t) {
    // TODO: edit here
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main() 
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    int N, K;
    cin >> N;
    vector<int64_t> a(N);
    cin >> K;
    vector<int64_t> t(K);
    for (int i = 0; i < N; ++i) {
        cin >> a[i];
    }
    for (int i = 0; i < K; ++i) {
        cin >> t[i];
    }
    auto ans = solveCase(N, K, a, t);
    cout << ans << endl;
    return 0;
}