#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;

string solveCase(int64_t N, string S, string X)
{
    // TODO: edit here
    vector<int> win_t(7);
    win_t[0] = 1;
    reverse(all(S));
    reverse(all(X));
    int curr = 1;
    for (size_t i = 0; i < N; i++)
    {
        int val = ((S[i] - '0') * curr) % 7;
        vector<int> win_next_t(7);
        for (size_t j = 0; j < 7; j++)
        {
            if (X[i] == 'T')
            {
                int now = (j + val) % 7;
                if (win_t[now])
                    win_next_t[j] = 1;
                else
                    win_next_t[j] = win_t[j];
            }
            else
            {
                int now = (j + val) % 7;
                if (!win_t[now])
                    win_next_t[j] = 0;
                else
                    win_next_t[j] = win_t[j];
            }
        }
        curr = (curr * 10) % 7;
        win_t = win_next_t;
        db(i, win_t, curr, val);
    }
    if (win_t[0])
        return "Takahashi";
    return "Aoki";
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main()
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    int N;
    string X, S;
    cin >> N >> S >> X;
    auto ans = solveCase(N, S, X);
    cout << ans << endl;
    return 0;
}