#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;

auto solveCase(int64_t N)
{
    // TODO: edit here
    vector<ll> ret(N + 1);
    vector<vector<int>> vecc(N + 1);
    for (ll i = 1; i <= N; i++)
    {
        set<int> ss;
        for (auto &x : vecc[i])
            if (ret[x] != -1)
                ss.insert(ret[x]);
        int now = 1;
        while (ss.count(now))
            ++now;
        ret[i] = now;
        db(i, now, ss, vecc);
        for (ll j = 2; i * j <= N; j++)
            vecc[i * j].pb(i);
    }
    return ret;
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main()
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    int64_t N;
    cin >> N;
    auto ans = solveCase(N);
    for (int i = 1; i <= N; ++i)
    {
        cout << ans[i] << ' ';
    }
    cout << endl;
    return 0;
}