#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;

int64_t solveCase(int N, int M, const vector<int64_t> &w, const vector<int64_t> &l, const vector<int64_t> &v)
{
    // TODO: edit here
    int64_t res = LLONG_MAX;
    sort(all(w));
    do
    {
        
    } while (next_permutation(all(w)));
    return res;
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main()
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    int N, M;
    cin >> N;
    vector<int64_t> w(N);
    cin >> M;
    vector<int64_t> l(M), v(M);
    for (int i = 0; i < N; ++i)
    {
        cin >> w[i];
    }
    for (int i = 0; i < M; ++i)
    {
        cin >> l[i] >> v[i];
    }
    auto ans = solveCase(N, M, w, l, v);
    cout << ans << endl;
    return 0;
}