#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;

void solveCase(int64_t A, int64_t B, int64_t W)
{
    // TODO: edit here
    W *= 1000;
    vector<set<pair<int, int>>> toadd(W + A + B + 1), torem(W + A + B + 1);
    set<pair<int, int>> curr;
    curr.insert({0, 0});
    torem[1].insert({0, 0});
    for (size_t i = 0; i <= W; i++)
    {
        for (auto &x : toadd[i])
            curr.insert(x);
        for (auto &x : torem[i])
            curr.erase(x);
        db(i, curr, toadd[i], torem[i]);
        if (curr.size())
        {
            auto mini = (curr.begin())->first;
            auto maxi = (curr.rbegin())->first;
            toadd[i + A].insert({mini + 1, i});
            torem[i + B + 1].insert({mini + 1, i});
            toadd[i + A].insert({maxi + 1, i});
            torem[i + B + 1].insert({maxi + 1, i});
        }
    }
    if (curr.size())
    {
        auto mini = (curr.begin())->first;
        auto maxi = (curr.rbegin())->first;
        cout << mini << ' ' << maxi << '\n';
    }
    else
        cout << "UNSATISFIABLE\n";
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main()
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    int64_t A, B, W;
    cin >> A >> B >> W;
    solveCase(A, B, W);
    return 0;
}