#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;

string solveCase(string s)
{
    // TODO: edit here
    auto it = find(all(s), '.');
    if (it == s.end())
        return s;
    s = s.substr(0,it-s.begin());
    return s;
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main()
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    string X;
    cin >> X;
    auto ans = solveCase(X);
    cout << ans << endl;
    return 0;
}