#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;

const string YES = "Yes";
const string NO = "No";
bool solveCase(int64_t A, int64_t B, int64_t C)
{
    // TODO: edit here
    return A * A + B * B < C * C;
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main()
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    int64_t A, B, C;
    cin >> A >> B >> C;
    auto ans = solveCase(A, B, C);
    cout << (ans ? YES : NO) << endl;
    return 0;
}