#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;


int64_t solveCase(auto N, const vector<vector<auto> > & c) {
    // TODO: edit here
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main() 
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    auto N;
    cin >> N;
    vector<vector<auto> > c(N, vector<auto>((N)));
    for (int j = 0; j < N; ++j) {
        for (int i = 0; i < N; ++i) {
            cin >> c[j][i];
        }
    }
    auto ans = solveCase(N, c);
    cout << ans << endl;
    return 0;
}