#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;

const string FIRST = "Alice";
const string SECOND = "Brown";

int dp[101][101];

int solve(int x, int y)
{
    assert(x >= 0 && y >= 0);
    auto &ret = dp[x][y];
    if (ret >= 0)
        return ret;
    if (x > y)
        swap(x, y);
    ret = 0;
    for (int now = 2; now <= x; now += 2)
        ret = ret || !solve(x - now, y + now / 2);
    for (int now = 2; now <= y; now += 2)
        ret = ret || !solve(x + now / 2, y - now);
    return ret;
}

string solveCase(int64_t X, int64_t Y)
{
    // TODO: edit here
    // memset(dp, -1, sizeof dp);
    // for (size_t i = 0; i <= X; i++)
    // {
    //     for (size_t j = 0; j <= Y; j++)
    //         cout << solve(i, j) << ' ';
    //     cout << '\n';
    //     /* code */
    // }
    return abs(X-Y) <= 1 ? SECOND : FIRST;
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main()
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    int64_t X, Y;
    cin >> X >> Y;
    auto ans = solveCase(X, Y);
    cout << ans << endl;
    return 0;
}