#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;

double solveCase(int64_t A, int64_t B)
{
    // TODO: edit here
    return (A - B) * 100.0 / A;
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main()
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    int64_t A, B;
    cin >> A >> B;
    auto ans = solveCase(A, B);
    cout << fixed << setprecision(10);
    cout << ans << endl;
    return 0;
}