#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;

constexpr int64_t MOD = 998244353;
int64_t solveCase(int64_t N, int M, const vector<int64_t>& a, const vector<int64_t>& b) {
    // TODO: edit here
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main() {
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    int N;
    int M;
    cin >> N >> M;
    vector<int64_t> a(M), b(M);
    for (int i = 0; i < M; ++i) {
        cin >> a[i] >> b[i];
    }
    auto ans = solveCase(N, M, a, b);
    cout << ans << endl;
    return 0;
}