#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;

const string YES = "Yes";
const string NO = "No";
bool solveCase(int64_t N)
{
    // TODO: edit here
    int cnt = 0;
    while (N)
    {
        if (N % 10 == 0)
        {
            N /= 10;
            cnt++;
        }
        else
            break;
    }
    auto N_str = to_string(N);
    auto N_rev = N_str;
    reverse(all(N_rev));
    if (N_str == N_rev)
        return 1;
    return 0;
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main()
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    int64_t N;
    cin >> N;
    auto ans = solveCase(N);
    cout << (ans ? YES : NO) << endl;
    return 0;
}