#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
// const int NAX = 2e5 + 5, MOD = 1000000007;

constexpr int64_t MOD = 998244353;
auto solveCase(int T, vector<int64_t> c)
{
    // TODO: edit here
    vector<string> res(c.size());
    for (size_t i = 0; i < c.size(); i++)
    {
        int tp = 0;
        while (c[i] % 2 == 0)
        {
            tp++;
            c[i] /= 2;
        }
        db(tp, c[i]);
        if (tp == 1)
            res[i] = "Same";
        else if (tp == 0)
            res[i] = "Odd";
        else
            res[i] = "Even";
    }
    db(res);
    return res;
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main()
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    int T;
    cin >> T;
    vector<int64_t> c(T);
    for (int i = 0; i < T; ++i)
    {
        cin >> c[i];
    }
    auto ans = solveCase(T, c);
    for (int i = 0; i < T; ++i)
    {
        cout << ans[i] << endl;
    }
    return 0;
}