#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;


auto solveCase(int N, int64_t K, const vector<int64_t> & P) {
    // TODO: edit here
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main() 
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    int64_t N;
    int64_t K;
    cin >> N;
    vector<int64_t> P(N);
    cin >> K;
    for (int i = 0; i < N; ++i) {
        cin >> P[i];
    }
    auto ans = solveCase(N, K, P);
    for (int i = 0; i < N; ++i) {
        cout << ans[i] << endl;
    }
    cout << endl;
    return 0;
}