#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
constexpr char endl = '\n';
const int NAX = 2e5 + 5, MOD = 1000000007;


int64_t solveCase(int N, const vector<int64_t> & x, const vector<int64_t> & y) {
    // TODO: edit here
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main() 
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    int N;
    cin >> N;
    vector<int64_t> x(N), y(N);
    for (int i = 0; i < N; ++i) {
        cin >> x[i] >> y[i];
    }
    auto ans = solveCase(N, x, y);
    cout << ans << endl;
    return 0;
}