#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;

int64_t solveCase(int N, int64_t M, const vector<string> &S)
{
    // TODO: edit here
    ll cntE = 0, cntO = 0, res = 0;
    for (size_t i = 0; i < N; i++)
    {
        int c = count(all(S[i]), '1');
        if (c & 1)
        {
            res += cntE;
            cntO++;
        }
        else
        {
            res += cntO;
            cntE++;
        }
    }
    return res;
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main()
{
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    int64_t N;
    int64_t M;
    cin >> N;
    vector<string> S(N);
    cin >> M;
    for (int i = 0; i < N; ++i)
    {
        cin >> S[i];
    }
    auto ans = solveCase(N, M, S);
    cout << ans << endl;
    return 0;
}