#include <bits/stdc++.h>
using namespace std;

#ifdef LOCAL
#include "/debug.h"
#else
#define db(...)
#endif

#define all(v) v.begin(), v.end()
#define pb push_back
using ll = long long;
const int NAX = 2e5 + 5, MOD = 1000000007;

int64_t solveCase(int N, int64_t K, const vector<int64_t>& u, const vector<int64_t>& v) {
    // TODO: edit here
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main() {
#ifndef LOCAL
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
#endif
    constexpr char endl = '\n';
    int64_t N;
    int64_t K;
    cin >> N;
    vector<int64_t> u(N - 1), v(N - 1);
    cin >> K;
    for (int i = 0; i < N - 1; ++i) {
        cin >> u[i] >> v[i];
    }
    auto ans = solveCase(N, K, u, v);
    cout << ans << endl;
    return 0;
}